[project]
name = "xno"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "cachetools>=6.2.1",
    "confluent-kafka>=2.11.1",
    "dotenv>=0.9.9",
    "ipython>=9.6.0",
    "pandas>=2.3.2",
    "plotly>=6.3.1",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.12.3",
    "quantstats>=0.0.77",
    "readerwriterlock>=1.0.9",
    "redis>=6.4.0",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.43",
    "tqdm>=4.67.1",
    "vnstock>=3.2.6",
]
